<a href="https://colab.research.google.com/github/payal0110-ds/BoW_LLM/blob/main/Trial1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive


In [10]:
from nltk import word_tokenize
from nltk import WordNetLemmatizer
from nltk.corpus import stopwords
from sklearn.feature_extraction.text import TfidfVectorizer
import pandas as pd
import numpy as np
import re

In [6]:
import nltk
nltk.download('wordnet')

[nltk_data] Downloading package wordnet to /root/nltk_data...


True

In [7]:
data=pd.read_csv("/content/drive/MyDrive/Colab Notebooks/music.txt",sep="\t",names=["caption"])
print(data)

                                        caption
0                     Music is something I love
1          When I feel happy, I listen to songs
2                  Music brings people together
3  Music understands emotions better than words
4           Songs are what make music the music
5               Songs stay in my mind and heart
6               Songs are the big part of music
7         Music make people cheer up their mood
8        Happy songs can change the entire mood
9                           Music is everywhere


In [9]:
corpus=[]
for i in range(len(data)):
  statement=re.sub("[^a-zA-Z]"," ",data["caption"][i])
  statement=statement.lower()
  statement=statement.split()
  statement=[WordNetLemmatizer().lemmatize(word) for word in statement
             if word not in set(stopwords.words('english'))]
  statement=" ".join(statement)
  corpus.append(statement)
print(corpus)

['music something love', 'feel happy listen song', 'music brings people together', 'music understands emotion better word', 'song make music music', 'song stay mind heart', 'song big part music', 'music make people cheer mood', 'happy song change entire mood', 'music everywhere']


In [12]:
tfidf=TfidfVectorizer(max_features=5)
matrix=tfidf.fit_transform(corpus)
X=matrix.toarray()
print(X)

[[0.         0.         0.         1.         0.        ]
 [0.81979472 0.         0.         0.         0.5726575 ]
 [0.         0.         0.         1.         0.        ]
 [0.         0.         0.         1.         0.        ]
 [0.         0.59727367 0.         0.68497676 0.41721817]
 [0.         0.         0.         0.         1.        ]
 [0.         0.         0.         0.63448879 0.77293206]
 [0.         0.65528915 0.65528915 0.37575559 0.        ]
 [0.63398466 0.         0.63398466 0.         0.44286217]
 [0.         0.         0.         1.         0.        ]]


In [13]:
# print(tfidf.vocabulary_)
features=tfidf.get_feature_names_out()
print(features)

['happy' 'make' 'mood' 'music' 'song']


In [15]:
df = pd.DataFrame(X, columns=features)
print(df)

      happy      make      mood     music      song
0  0.000000  0.000000  0.000000  1.000000  0.000000
1  0.819795  0.000000  0.000000  0.000000  0.572658
2  0.000000  0.000000  0.000000  1.000000  0.000000
3  0.000000  0.000000  0.000000  1.000000  0.000000
4  0.000000  0.597274  0.000000  0.684977  0.417218
5  0.000000  0.000000  0.000000  0.000000  1.000000
6  0.000000  0.000000  0.000000  0.634489  0.772932
7  0.000000  0.655289  0.655289  0.375756  0.000000
8  0.633985  0.000000  0.633985  0.000000  0.442862
9  0.000000  0.000000  0.000000  1.000000  0.000000
